In [2]:
from sklearn import svm
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
data = pd.read_csv('glass.csv')
y = data['Type']
x = data.drop('Type', 1)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25)
linear = svm.SVC(kernel='linear')
linear.fit(xtrain, ytrain)
ypred1 = linear.predict(xtest)
#print(linear.support_vectors_)
#print(linear.n_support_)
print("Accuracy Of Linear Kernel: ", accuracy_score(ytest, ypred1))
print("Confusion Matrix: \n", confusion_matrix(ytest, ypred1))
print("Classification report: \n", classification_report(ytest, ypred1))
sigmoid = svm.SVC(kernel='sigmoid')
poly = svm.SVC(kernel='poly')
rbf = svm.SVC(kernel='rbf')
sigmoid.fit(xtrain, ytrain)
poly.fit(xtrain, ytrain)
rbf.fit(xtrain, ytrain)
ypred2 = sigmoid.predict(xtest)
ypred3 = poly.predict(xtest)
ypred4 = rbf.predict(xtest)
print("Accuracy Of Sigmoid Kernel: ", accuracy_score(ytest, ypred2))
print("Accuracy Of Ploy Kernel: ", accuracy_score(ytest, ypred3))
print("Accuracy Of RBF Kernel: ", accuracy_score(ytest, ypred4))


C:\Users\lenovo\AppData\Local\Temp/ipykernel_31320/3551924494.py:8: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  x = data.drop('Type', 1)


Accuracy Of Linear Kernel:  0.9814814814814815
Confusion Matrix: 
 [[16  0  0  0  0  0]
 [ 0 20  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  4  1  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  6]]
Classification report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        20
           3       1.00      1.00      1.00         6
           5       1.00      0.80      0.89         5
           6       0.50      1.00      0.67         1
           7       1.00      1.00      1.00         6

    accuracy                           0.98        54
   macro avg       0.92      0.97      0.93        54
weighted avg       0.99      0.98      0.98        54

Accuracy Of Sigmoid Kernel:  0.6296296296296297
Accuracy Of Ploy Kernel:  0.9444444444444444
Accuracy Of RBF Kernel:  0.7592592592592593
